#!/bin/bash 

SSHFS_ROOT="$HOME/sshfs"
PERSISTENT_CHECK_TIMEOUT=5


if [ "$1" == '' ] ; then
    echo "Usage: $0 user@host:remotepath - Single mount"
    echo 'Sample: `sfs guest@example.com:` - mounts home directory of guest on exapmle.com into your home on localhost in folder sshfs: ~/sshfs/example.com/guest/'
    echo "Usage: $0 user@host:remotepath -p & - Persistent mount"
    echo 'Sample: `sfs guest@example.com: -p &` - Same as previous sample, but sfs works in background and checks for some files in local mount directory. If there no files found'
    echo '       it tries to remount remote directory again. Useful for non-stable connections like fucking ukrtelecom or GPRS.'
    echo '       REQUIRES SSH KEY AUTHENTICATION FOR PROMPTLESS sshfs MOUNT'
    exit 1
fi

USER=`echo $1 | cut -f 1 -d '@'`
echo "User: $USER"
HOST=`echo $1 | cut -f 2 -d '@'`
HOST=`echo $HOST | cut -f 1 -d ':'`
echo "Host: $HOST"

SSHFS_PATH="$SSHFS_ROOT/$HOST/$USER"

mkdir -p $SSHFS_PATH > /dev/null 2>&1
sshfs $1 $SSHFS_PATH

if [ "$2" == '-p' ] ; then
    echo "Persistent mode. Are you sure that you already set your public key on $1 ?"
    while true ; do
        sshfs $1 $SSHFS_PATH > /dev/null 2>&1
        sleep $PERSISTENT_CHECK_TIMEOUT
    done
fi
